services:
  db:
    image: mysql:8.4
    # image: mysql:latest
    container_name: mysql_db
    restart: always
    env_file:
      - .env  # Load env variables from root .env file
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
    networks:
      - my_network
    # Adds healthcheck so the server image runs later. Note: Delete this if any issues arise.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 20s


  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
    env_file:
      - ./server/.env.server
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  # frontend:
  #   build: ./frontend
  #   container_name: my_frontend
  #   depends_on:
  #     - server
  #   ports:
  #     - "5173:5173"  # Vite default port
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   command: ["npm", "run", "dev"]

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge