services:
  db:
    image: mysql:8.4
    # image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gotcha_games
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # server:
  #   build: ./server
  #   container_name: my_backend
  #   depends_on:
  #     - db
  #   env_file: ./server/.env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules
  #   command: ["node", "dist/index.js"]

  # frontend:
  #   build: ./frontend
  #   container_name: my_frontend
  #   depends_on:
  #     - server
  #   ports:
  #     - "5173:5173"  # Vite default port
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   command: ["npm", "run", "dev"]

volumes:
  mysql_data:
