services:
  db:
    image: mysql:8.4
    # image: mysql:latest
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gotcha_games
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./db/02_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    # Adds healthcheck so the server image runs later. Note: Delete this if any issues arise.
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 20s


  server:
    build: ./server
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    env_file: ./server/.env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "run", "start"]

  # frontend:
  #   build: ./frontend
  #   container_name: my_frontend
  #   depends_on:
  #     - server
  #   ports:
  #     - "5173:5173"  # Vite default port
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   command: ["npm", "run", "dev"]

volumes:
  mysql_data:
