import { apiAdapter } from "./apiAdapter";
import { Customer } from "../types/Customer";

// Retrieve all customers
export const getCustomers = async (): Promise<Customer[]> => {
  return apiAdapter.get<Customer[]>("/api/customers");
};

// Create a new customer (customerID is auto-generated by the backend)
export const createCustomer = async (
  customer: Omit<Customer, "customerID">
): Promise<Customer> => {
  return apiAdapter.post<Customer>("/api/customers", customer);
};

// Update an existing customer by ID
export const updateCustomer = async (
  id: number,
  data: Partial<Customer>
): Promise<Customer> => {
  return apiAdapter.patch<Customer>(`/api/customers/${id}`, data);
};

// Delete a customer by ID
export const deleteCustomer = async (id: number): Promise<void> => {
  return apiAdapter.delete(`/api/customers/${id}`);
};
