import { apiAdapter } from "./apiAdapter";
import { CustomersHaveGames } from "../types/CustomerHasGame";

// Retrieve all records
export const getCustomersHaveGames = async (): Promise<CustomersHaveGames[]> => {
  return apiAdapter.get<CustomersHaveGames[]>("/api/customers-have-games");
};

// Create a new record (the customersHaveGamesID is auto-generated by the backend)
export const createCustomersHaveGames = async (
  record: Omit<CustomersHaveGames, "customersHaveGamesID">
): Promise<CustomersHaveGames> => {
  const response = await apiAdapter.post<CustomersHaveGames>("/api/customers-have-games", record);
  
  // Extra error handling for adapter
  if (!response) {
    throw new Error("No response from create endpoint");
  }
  return response;
};

// Update an existing record by ID
export const updateCustomersHaveGames = async (
  id: number,
  data: Partial<CustomersHaveGames>
): Promise<CustomersHaveGames> => {
  return apiAdapter.patch<CustomersHaveGames>(`/api/customers-have-games/${id}`, data);
};

// Delete a record by ID
export const deleteCustomersHaveGames = async (id: number): Promise<void> => {
  return apiAdapter.delete(`/api/customers-have-games/${id}`);
};
