import { apiAdapter } from "./apiAdapter";
import { Game } from "../types/Game";

// Retrieve all games
export const getGames = (): Promise<Game[]> =>
  apiAdapter.get<Game[]>("/api/games");

// Create new game (gameID is auto-generated by MySQL on the backend)
export const createGame = (game: Omit<Game, "gameID">): Promise<Game> =>
  apiAdapter.post<Game>("/api/games", game);

// Update existing game by ID
export const updateGame = (id: number, data: Partial<Game>): Promise<Game> =>
  apiAdapter.patch<Game>(`/api/games/${id}`, data);

// Delete game by ID
export const deleteGame = (id: number): Promise<void> =>
  apiAdapter.delete(`/api/games/${id}`);
