import { apiAdapter } from "./apiAdapter";
import { ServicePlatform } from "../types/ServicePlatform";

// Retrieve all service platform records
export const getServicePlatforms = async (): Promise<ServicePlatform[]> =>
  apiAdapter.get<ServicePlatform[]>("/api/serviceplatforms");

// Create new service platform record. The platform ID is auto-generated by MySQL and the backend
export const createServicePlatform = async (
  platform: Omit<ServicePlatform, "servicePlatformID">
): Promise<ServicePlatform> =>
  apiAdapter.post<ServicePlatform>("/api/serviceplatforms", platform);

// Update existing service platform record by ID
export const updateServicePlatform = async (
  id: number,
  data: Partial<ServicePlatform>
): Promise<ServicePlatform> =>
  apiAdapter.patch<ServicePlatform>(`/api/serviceplatforms/${id}`, data);

// Delete service platform record by ID
export const deleteServicePlatform = async (id: number): Promise<void> =>
  apiAdapter.delete(`/api/serviceplatforms/${id}`);
