name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies in the root so that the root's node_modules exists (might fix CI Prettier recognization issue)
      - name: Install root dependencies
        run: npm install

      # Backend linting
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Force Install eslint-plugin-prettier
        working-directory: ./server
        run: npm install eslint-plugin-prettier --save-dev

      # Debugging step to check if dependencies are installed correctly
      - name: Debug Backend Dependencies
        working-directory: ./server
        run: npm list

      - name: Run Backend ESLint (in debug mode)
        working-directory: ./server
        run: npm run lint -- --debug

      - name: Run Backend Prettier
        working-directory: ./server
        run: npm run prettier:fix

      # Frontend linting (commented out for now)
      # - name: Install frontend dependencies
      #   working-directory: ./frontend
      #   run: npm install

      # - name: Run Frontend ESLint
      #   working-directory: ./frontend
      #   run: npm run lint

      # - name: Run Frontend Prettier
      #   working-directory: ./frontend
      #   run: npm run prettier:fix
